version: '3'

services:
  web:
    build: .
    command: python main.py
    volumes:
      - .:/code
    ports:
      - "8888:8888"

  dynamodb:
    restart: always
    image: cnadiminti/dynamodb-local
    container_name: dynamodb
    ports:
      - 7000:8000
    volumes:
      - ./dynamodb_local_db:/dynamodb_local_db

  dynamodbadmin:
    depends_on:
      - dynamodb
    restart: always
    image: aaronshaf/dynamodb-admin
    container_name: dynamoadmin
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    ports:
      - 7001:8001
    links:
      - dynamodb:dynamo_db
